name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs: 
  run-formatter:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4

      - name: Spell check
        uses: crate-ci/typos@master
        with:
          write_changes: false
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10

      - run: |
          echo "RUSTC_WRAPPER=$RUSTC_WRAPPER"
          which sccache || true

      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Run cargo deny
        run: cargo deny check

      - name: Run cargo clippy and error on warnings
        run: cargo clippy -- -D warnings

      - name: Run cargo clippy and error on warnings
        run: cargo doc --all-features

      - name: Run build
        run: cargo build --all-features
  